### ISSUE TITLE
Apple Silicon support

### ISSUE THREAD

**Issue by MehediH** [felixrieseberg/macos-notification-state#21]
Thank you for the work on this library! Would really appreciate it if I could get some help on getting this working on Apple Silicon devices :) 

I am hitting the following error:

```
Uncaught Exception:
Error: dlopen(/var/folders/_8/s6kwly554pv17pfc62lmd_900000gn/T/.com.MehediHassan.Tweeten.CHsGoi, 1): no suitable image found.  Did find:
/var/folders/_8/s6kwly554pv17pfc62lmd_900000gn/T/.com.MehediHassan.Tweeten.CHsGoi: mach-o, but wrong architecture
/var/folders/_8/s6kwly554pv17pfc62lmd_900000gn/T/.com.MehediHassan.Tweeten.CHsGoi: stat() failed with errno=17
at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
at Object.func [as .node] (electron/js2c/asar_bundle.js:5:2073)
at Module.load (internal/modules/cjs/loader.js:935:32)
at Module._load (internal/modules/cjs/loader.js:776:14)
at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
at Module.require (internal/modules/cjs/loader.js:959:19)
at require (internal/modules/cjs/helpers.js:88:18)
at bindings (/Applications/Tweeten.app/Contents/Resources/app-arm64.asar/node_modules/bindings/bindings.js:112:48)
at Object.<anonymous> (/Applications/Tweeten.app/Contents/Resources/app-arm64.asar/node_modules/macos-notification-state/lib/index.js:1:34)
```

Note that I am trying to build the ARM64 app on an Intel machine, I am unsure as to whether the behaviour would be different if I was to build it on an Apple Silicon device. 

Thanks!

**Comment by DariusNorv** [comment]
@felixrieseberg please take a look at PR below. It helped me to support arm64

**Comment by viktor44** [comment]
@felixrieseberg `macos-notification-state 3.0.0` causes application crash on Apple M1
MacOS 13.6
This fork doesn't cause crash https://github.com/stack-inc/macos-notification-state
But `getDoNotDisturb()` is always `false`
