### ISSUE TITLE
Arm64 support

### ISSUE THREAD

**Issue by NunoCuradoFuze** [felixrieseberg/macos-notification-state#25]
Building an application for arm 64 architecture using this library as dependency is failing with this following error:

```
electron-builder -m --arm64 --config build-config-desktop.json --publish never
  • electron-builder  version=22.11.8 os=19.6.0
  • loaded configuration  file=/Users/ncurado/client-electron/build-config-desktop.json
  • description is missed in the package.json  appPackageFile=/Users/ncurado/client-electron/package.json
  • writing effective config  file=dist/builder-effective-config.yaml
  • rebuilding native dependencies  dependencies=macos-notification-state@1.3.6, node-hid@2.1.1, windows-focus-assist@1.2.1 platform=darwin arch=arm64
  • install prebuilt binary  name=node-hid version=2.1.1 platform=darwin arch=arm64 napi=
  ⨯ cannot execute  cause=exit status 1
                    out=
    > macos-notification-state@1.3.6 install /Users/ncurado/client-electron/node_modules/macos-notification-state
    > node-gyp rebuild
    
      CXX(target) Release/obj.target/notificationstate/lib/notificationstate.o
    
                    errorOut=In file included from ../lib/notificationstate.cc:2:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/node_api.h:12:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api.h:24:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api_types.h:8:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdint.h:123:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:32:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/cdefs.h:807:2: error: Unsupported architecture
    #error Unsupported architecture
     ^
    In file included from ../lib/notificationstate.cc:2:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/node_api.h:12:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api.h:24:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api_types.h:8:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdint.h:123:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:33:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/_types.h:34:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from ../lib/notificationstate.cc:2:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/node_api.h:12:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api.h:24:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api_types.h:8:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdint.h:123:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:55:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_blkcnt_t;      /* total blocks */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:56:9: error: unknown type name '__int32_t'
    typedef __int32_t       __darwin_blksize_t;     /* preferred block size */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:57:9: error: unknown type name '__int32_t'
    typedef __int32_t       __darwin_dev_t;         /* dev_t */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:60:9: error: unknown type name '__uint32_t'
    typedef __uint32_t      __darwin_gid_t;         /* [???] process and group IDs */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:61:9: error: unknown type name '__uint32_t'
    typedef __uint32_t      __darwin_id_t;          /* [XSI] pid_t, uid_t, or gid_t*/
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:62:9: error: unknown type name '__uint64_t'; did you mean 'uint64_t'?
    typedef __uint64_t      __darwin_ino64_t;       /* [???] Used for 64 bit inodes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/_types/_uint64_t.h:31:28: note: 'uint64_t' declared here
    typedef unsigned long long uint64_t;
                               ^
    In file included from ../lib/notificationstate.cc:2:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/node_api.h:12:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api.h:24:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api_types.h:8:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdint.h:123:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:52:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:68:9: error: unknown type name '__darwin_natural_t'
    typedef __darwin_natural_t __darwin_mach_port_name_t; /* Used by mach */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:70:9: error: unknown type name '__uint16_t'
    typedef __uint16_t      __darwin_mode_t;        /* [???] Some file attributes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:71:9: error: unknown type name '__int64_t'
    typedef __int64_t       __darwin_off_t;         /* [???] Used for file sizes */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:72:9: error: unknown type name '__int32_t'
    typedef __int32_t       __darwin_pid_t;         /* [???] process and group IDs */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:73:9: error: unknown type name '__uint32_t'
    typedef __uint32_t      __darwin_sigset_t;      /* [???] signal set */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:74:9: error: unknown type name '__int32_t'
    typedef __int32_t       __darwin_suseconds_t;   /* [???] microseconds */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:75:9: error: unknown type name '__uint32_t'
    typedef __uint32_t      __darwin_uid_t;         /* [???] user IDs */
            ^
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types.h:76:9: error: unknown type name '__uint32_t'
    typedef __uint32_t      __darwin_useconds_t;    /* [???] microseconds */
            ^
    In file included from ../lib/notificationstate.cc:2:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/node_api.h:12:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api.h:24:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api_types.h:8:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdint.h:123:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:53:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_intptr_t.h:30:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported
     ^
    In file included from ../lib/notificationstate.cc:2:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/node_api.h:12:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api.h:24:
    In file included from /Users/ncurado/.electron-gyp/13.2.0/include/node/js_native_api_types.h:8:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/stdint.h:123:
    In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/12.0.0/include/stdint.h:52:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/stdint.h:53:
    /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/sys/_types/_intptr_t.h:32:9: error: unknown type name '__darwin_intptr_t'
    typedef __darwin_intptr_t       intptr_t;
            ^
    18 errors generated.
    make: *** [Release/obj.target/notificationstate/lib/notificationstate.o] Error 1
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:375:28)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
    gyp ERR! System Darwin 19.6.0
    gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /Users/ncurado/client-electron/node_modules/macos-notification-state
    gyp ERR! node -v v14.17.3
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok 
    npm ERR! code ELIFECYCLE
    npm ERR! errno 1
    npm ERR! macos-notification-state@1.3.6 install: `node-gyp rebuild`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the macos-notification-state@1.3.6 install script.
```
 

Is this an error due to unsupported arm64?

**Comment by felixrieseberg** [comment]
You seem to have the wrong SDK installed!
