### ISSUE TITLE
Cannot build module for node 10.15.3 (Electron 4) anymore

### ISSUE THREAD

**Issue by aabuhijleh** [felixrieseberg/macos-notification-state#5]
The module was building fine with @1.2.0.  Now, I get lots of errors when trying to install and build the module.

```sh
..\lib\notificationstate.cc(44): error C2653: 'Nan': is not a class or namespace name [<project_path>\node_modules\macos-notif
ication-state\build\notificationstate.vcxproj]
..\lib\notificationstate.cc(44): error C3861: 'GetFunction': identifier not found [<project_path>\node_modules\macos-notificat
ion-state\build\notificationstate.vcxproj]
..\lib\notificationstate.cc(44): error C2228: left of '.ToLocalChecked' must have class/struct/union [<project_path>\node_modu
les\macos-notification-state\build\notificationstate.vcxproj]
    ..\lib\notificationstate.cc(44): note: type is 'unknown-type'
..\lib\notificationstate.cc(44): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'v8::Set' [<project_path>\node_modules\macos-notification-state\build\notificationstate.vcxproj]
    ..\lib\notificationstate.cc(44): note: No constructor could take the source type, or constructor overload resolution was ambiguous
..\lib\notificationstate.cc(48): error C2653: 'Nan': is not a class or namespace name [<project_path>\node_modules\macos-notif
ication-state\build\notificationstate.vcxproj]
..\lib\notificationstate.cc(48): error C3861: 'GetFunction': identifier not found [<project_path>\node_modules\macos-notificat
ion-state\build\notificationstate.vcxproj]
..\lib\notificationstate.cc(48): error C2228: left of '.ToLocalChecked' must have class/struct/union [<project_path>\node_modu
les\macos-notification-state\build\notificationstate.vcxproj]
    ..\lib\notificationstate.cc(48): note: type is 'unknown-type'
..\lib\notificationstate.cc(48): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'v8::Set' [<project_path>\node_modules\macos-notification-state\build\notificationstate.vcxproj]
    ..\lib\notificationstate.cc(48): note: No constructor could take the source type, or constructor overload resolution was ambiguous
```

macos-notification-state@1.2.2
node@10.15.3
electron@4.1.0

**Comment by kennethlynne** [comment]
I got this: 
```
App threw an error during load
Error: The module './node_modules/macos-notification-state/build/Release/notificationstate.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (./node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (./node_modules/macos-notification-state/lib/index.js:1:189)
```
and npm rebuild does not fix it.

macos-notification-state: 1.2.0
Electron: 4.1.3
Node: 10.15.3

**Comment by aabuhijleh** [comment]
@kennethlynne 

This is not the same issue. You need to use [electron-rebuild](https://www.npmjs.com/package/electron-rebuild) and it should work out.

**Comment by kennethlynne** [comment]
Ok thanks @aabuhijleh !
